### ISSUE TITLE
Get application working on Linux

### ISSUE THREAD

**Issue by KR155E** [VUEngine/VUEngine-Studio#23]
Hasn't been tested on Linux so far.

- [x] Set up Linux VM for building
- [x] Test extensively

**Comment by DaVince** [comment]
I've built the application for Linux and installed the resulting .deb on Ubuntu 22.04. It opens up, but building is impossible, because the program installs into a path that contains spaces:
![image](https://user-images.githubusercontent.com/105533/183289638-96d4938c-4441-4050-b9ec-2485a712d9ff.png)

**Comment by DaVince** [comment]
I tried the AppImage next. It starts building and gets to "Building core", at which point it fails on permission errors.
![image](https://user-images.githubusercontent.com/105533/183289773-4974fe78-4395-407a-bbe0-06de262ca4c0.png)
